- src/demo.js
- src/style.css
- src/timeline.js
- src/utils/itemUtils.js
VISIBLE_START, VISIBLE_END, ITEM_HEIGHT now props
> Replace constants with props

- src/demo.js
- src/timeline.js
- src/utils/itemUtils.js
SelectedItems prop added
Basic selected CSS example introduced
ItemClickHandler added
Demo updated
> Work in progress

- package.json
- src/demo.js
- yarn.lock
Just a first drop that allows for the configuration of timeline params.
Still need to add zoom
> Better demo page

- src/components/timebar.js
- src/consts/timebarConsts.js
- src/demo.js
> Fix timbar resolution

- README.md
- src/demo.js
- src/style.css
- src/timeline.js
- src/utils/itemUtils.js
- src/utils/timeUtils.js
New utility added, getSnapPixelFromDelta i'll add a test for that if you think I haven't duplicated an existing function
* Snapping during drag and resizing added
* Single, double & Context clicks added as callbacks
* Demo updated to add an item on double click
* Added css to remove user text selection after a double click.
> Added snapping & callbacks

- src/timeline.js
- src/utils/timeUtils.js
Set the resize to the min snapping distance.
> Resize to minimum snap distance

- src/demo.js
- src/demo/customRenderers.js
- src/timeline.js
set changed to regenerate which creates items between the start and end
adding a new item to the timeline now respects the demo durations
removed the guard condition on willReceiveProps to always re-render
> updated demo

- src/timeline.js
> Selection box only triggered in grid (not in groups)

- src/timeline.js
See https://github.com/facebook/react/issues/4533
> Fix refs issue.

- .github/PULL_REQUEST_TEMPLATE.md
- .travis.yml
Hello <%= name %>!
Remember to increment the version number in `package.json` :)
> Travis fix

- src/components/timebar.js
- src/timeline.js
> Make time format customizable

- src/demo.js
- src/timeline.js
- src/utils/itemUtils.js
> Remove logging

- src/components/timebar.js
- src/timeline.js
FIxes #106
Fixes timebar rendering issue when only part of the time segment is visible.
**Before**
**Now**
> Fix up timebar bug

- README.md
- src/demo.js
- src/timeline.js
> Fixes #104

- src/components/timebar.js
> Fix month counting error

- src/components/timebar.js
Ensure only a single time-cursor is shown on the top time bar
> Single cursor

- src/components/timebar.js
- src/demo.js
- src/style.css
- src/timeline.js
> Add group title renderer

- src/style.css
> Fix styling for group title

- src/components/timebar.js
* Less duplicate code
* Fixed some bugs along the way
> Re-did the timebar renderer

- README.md
- package.json
- src/components/timebar.js
- src/demo.js
- src/style.css
- src/timeline.js
* Add a group title renderer
* Fix edge case bug for timebar
> Release v1.0.7

- package.json
- webpack.demo.prod.js
- yarn.lock
Fix for #128 - smaller demo bundle
> Smaller demo build

- src/timeline.js
> Throttle mouse

- package.json
- src/timeline.js
- src/utils/itemUtils.js
Change it so only selected items can be interacted with
> Selection fix

- package.json
- src/timeline.js
- src/utils/itemUtils.js
- Make it so that only selected items can be dragged & resized
> Release v1.0.9

- package.json
- src/timeline.js
Hotfix: onclick item events aren't coming through
> Fixes #135

- package.json
- Item click events not going through
> Release 1.0.10

- package.json
- src/components/selector.js
- src/components/selector.test.js
- src/setupTests.js
- src/timeline.js
- yarn.lock
> Fix selection box bug

- src/components/timebar.js
- src/timeline.js
> Fixes #138

- CHANGELOG.md
- package.json
Requires #147  and #146  to be merged
> Update package & changelog

- package.json
> Package bump

- CHANGELOG.md
- package.json
- yarn.lock
> Release 1.0.15

- package.json
- yarn.lock
> updated dependency versions

- package.json
- yarn.lock
> v1.0.16 to npm

- .gitignore
push change to .gitignore to force rebuild
> 1.0.16 to npm part 2

- package.json
same code as alpha.1 trying to do a beta release and see if npm will accept it
> NPM 1.1.0-beta.1

- CHANGELOG.md
- package.json
- src/timeline.js
- src/utils/itemUtils.js
> v1.1.1 - bugfix for selection ui

- src/timeline.js
Pass resolution props to timeline
- [] New feature
- [] I have added tests that prove my fix is effective or that my feature works
- [] I have added necessary documentation (if appropriate)
> Allow timeline custom resolution

- src/components/body.js
- src/demo.js
- src/style.css
- src/timeline.js
> TimelineBody height fix + remove page scroll from demo

- src/components/renderers.js
- src/components/timebar.js
- src/consts/timebarConsts.js
- src/demo.js
- src/timeline.js
- src/utils/itemUtils.js
- src/utils/timeUtils.js
- src/utils/timeUtils.test.js
I'm a collaborator with @cristian-spiescu.
Cf. #196
> seconds and milliseconds support for gantt

- .storybook/.babelrc
- .storybook/main.js
- .storybook/preview.js
- package.json
- src/demo.html
- src/demo.js
- src/stories/Timeline.stories.jsx
- src/style.css
- yarn.lock
Added Storybook
_Put an `x` in the boxes that apply_
> Added Storybook

- src/timeline.js
cf. #196
_Put an `x` in the boxes that apply_
- [X ] Bugfix
> replace pixelsPerSecond function call

- docs/table-columns.md
- src/components/body.js
- src/components/renderers.js
- src/components/renderers.test.js
- src/components/timebar.js
- src/demo.js
- src/demo/customRenderers.js
- src/style.css
- src/timeline.js
> Added multiple columns / table.

- package.json
- src/components/body.js
- webpack.demo.prod.js
- webpack.dev.js
- webpack.prod.js
- yarn.lock
- Was having issues running the dev server on osx
- Bumping webpack seems to have resolved it
_Put an `x` in the boxes that apply_
> Bump webpack

- README.md
- docs/date-types.md
- src/demo.js
- src/timeline.js
- src/utils/itemUtils.js
- src/utils/itemUtils.test.js
- src/utils/timeUtils.js
- src/utils/timeUtils.test.js
> Added "useMoment". Dates can now also be timestams (millis). Not only

- src/stories/Timeline.stories.jsx
- src/style.css
Added stuff in the storybook area. More precisely some doc:
> Added some doc in storybook for "useMoment"
